name: File Repository Transfer

on:
  workflow_dispatch:
    inputs:
      source_repo:
        description: 'Source Repository (owner/repo)'
        required: true
        default: 'jwrdegoede/rtl8189ES_linux'
      target_repo:
        description: 'Target Repository (owner/repo)'
        required: true
        default: 'xidz-repo/linux-6.12.y'
      target_path:
        description: 'Target Path'
        required: true
        default: 'drivers/net/wireless/realtek/rtl8189fs'

jobs:
  transfer:
    runs-on: ubuntu-latest
    steps:
    - name: Transfer Files
      env:
        PAT_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        # Validasi token
        if [ -z "$PAT_TOKEN" ]; then
          echo "Error: PERSONAL_ACCESS_TOKEN not found in secrets"
          echo "Please create a Personal Access Token with 'repo' scope"
          echo "and add it to repository secrets as 'PERSONAL_ACCESS_TOKEN'"
          exit 1
        fi
        
        # Setup git dengan PAT
        git config --global user.name "GitHub Action Transfer"
        git config --global user.email "action@github.com"
        git config --global credential.helper store
        echo "https://${PAT_TOKEN}@github.com" > ~/.git-credentials
        
        # Clone source
        echo "Cloning source repository: ${{ github.event.inputs.source_repo }}"
        git clone https://github.com/${{ github.event.inputs.source_repo }}.git source
        cd source
        
        # Auto-detect branch
        BRANCH=$(git symbolic-ref refs/remotes/origin/HEAD 2>/dev/null | sed 's@^refs/remotes/origin/@@' || echo "master")
        echo "Detected branch: $BRANCH"
        git checkout $BRANCH || git checkout master || git checkout main
        echo "Current branch: $(git branch --show-current)"
        cd ..
        
        # Clone target dengan PAT
        echo "Cloning target repository: ${{ github.event.inputs.target_repo }}"
        git clone https://${PAT_TOKEN}@github.com/${{ github.event.inputs.target_repo }}.git target
        cd target
        
        # Setup target branch
        CURRENT_BRANCH=$(git branch --show-current)
        echo "Target current branch: $CURRENT_BRANCH"
        cd ..
        
        # Copy files (INCLUDE .github folder)
        echo "Creating target directory: ${{ github.event.inputs.target_path }}"
        mkdir -p target/${{ github.event.inputs.target_path }}
        
        echo "Copying files (including .github/workflows)..."
        rsync -av \
          --exclude='.git/' \
          --include='.github/' \
          --include='.github/workflows/' \
          --include='.github/workflows/**' \
          source/ target/${{ github.event.inputs.target_path }}/
        
        # Show what was copied
        echo "Files copied:"
        find target/${{ github.event.inputs.target_path }} -name ".*" -type d
        find target/${{ github.event.inputs.target_path }}/.github -type f 2>/dev/null || echo "No .github files found"
        
        # Commit and push
        echo "Committing changes..."
        cd target
        git add .
        
        if ! git diff --cached --quiet; then
          git commit -m "Add files from ${{ github.event.inputs.source_repo }}
          
          Source: https://github.com/${{ github.event.inputs.source_repo }}
          Target Path: ${{ github.event.inputs.target_path }}
          Date: $(date -u '+%Y-%m-%d %H:%M:%S UTC')
          
          Includes .github/workflows directory"
          
          echo "Pushing changes..."
          git push origin HEAD
          echo "Transfer completed successfully!"
        else
          echo "No changes to commit"
        fi
        
        # Cleanup credentials
        rm -f ~/.git-credentials
        cd .. && rm -rf source target
        echo "Cleanup completed!"